### ISSUE TITLE
cityscapes

### ISSUE THREAD

**Issue by wanghangege** [AmirMansurian/AttnFD#3]
Hi, is cityscapes not fully available in this repository? After changing the data set to cityscapes, the path is incorrect.

**Comment by AmirMansurian** [comment]
Hi

Thank you for your message. Yes, the codebase works on Pascal for now. I will update the repo for Cityscapes, COCO and CamVid soon.

**Comment by wanghangege** [comment]
Thank you for your work, it’s great! Looking forward to your updates.
